[package]
name = "persistent_stack"
version = "0.1.0"
license = "MIT"
authors = ["timcryt <tymcrit@gmail.com>"]
edition = "2018"
description = "Concurrent persistent stack"
repository = "https://github.com/timcryt/persistent_stack"

[dependencies]
